In [21]:
import cv2
import numpy

In [7]:
im_g = cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [9]:
newimg = cv2.imwrite("newimage.png", im_g)

In [10]:
im_g[0:2, 2:4] #indexing in numpy array

array([[104, 121],
       [255, 255]], dtype=uint8)

In [11]:
im_g[2,4]

182

In [12]:
#Iterating in numpy array

for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [13]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [14]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [19]:
for i in im_g: 
    for j in im_g:
        print(i,j)

[187 158 104 121 143] [187 158 104 121 143]
[187 158 104 121 143] [198 125 255 255 147]
[187 158 104 121 143] [209 134 255  97 182]
[198 125 255 255 147] [187 158 104 121 143]
[198 125 255 255 147] [198 125 255 255 147]
[198 125 255 255 147] [209 134 255  97 182]
[209 134 255  97 182] [187 158 104 121 143]
[209 134 255  97 182] [198 125 255 255 147]
[209 134 255  97 182] [209 134 255  97 182]


In [22]:
ims = numpy.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
newsplt = numpy.hsplit(ims, 2)
print(newsplt)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [26]:
new1 = numpy.vsplit(ims,3)
print(new1)

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]
